/* Houses presets. Each entry is a name plus the settings (v) it applies on top of the defaults. */
import { H0 } from './defaults.js';

export const HOUSE_PRESETS = [
  {
    name: 'Brick colonial',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'gable',
      width: 30,
      depth: 22,
      stories: 2,
      storyH: 9,
      found: 1.5,
      pitch: 8,
      eave: 1,
      rake: 0.75,
      wallFinish: 'brick',
      roofFinish: 'asphalt',
      wallColor: '#9a4a38',
      trimColor: '#f3f0e8',
      roofColor: '#4b5056',
      windowColor: '#f3f0e8',
      doorColor: '#22382c',
      shutterColor: '#1f2a24',
      accentColor: '#22382c',
      shutters: true,
      chimney: true
    }
  },
  {
    name: 'Clapboard colonial',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'gable',
      width: 32,
      depth: 24,
      stories: 2,
      storyH: 9,
      found: 1.5,
      pitch: 9,
      eave: 0.75,
      rake: 0.5,
      wallFinish: 'siding',
      roofFinish: 'shake',
      wallColor: '#f0eee7',
      trimColor: '#ffffff',
      roofColor: '#4a4541',
      windowColor: '#ffffff',
      doorColor: '#1f3b5c',
      shutterColor: '#1f2a24',
      accentColor: '#1f3b5c',
      shutters: true,
      chimney: true
    }
  },
  {
    name: 'Haunted house',
    v: {
      ...H0,
      foot: 'T',
      roof: 'gable',
      width: 30,
      depth: 24,
      wingW: 12,
      wingP: 8,
      stories: 2,
      storyH: 10,
      found: 2.5,
      pitch: 14,
      eave: 1,
      rake: 0.75,
      wallFinish: 'siding',
      roofFinish: 'fish',
      wallColor: '#5b5566',
      trimColor: '#2b2830',
      roofColor: '#27242b',
      windowColor: '#1b1a1f',
      doorColor: '#3d1f2b',
      shutterColor: '#2b2830',
      accentColor: '#6b2f3a',
      shutters: true,
      tower: true,
      boarded: true,
      lit: true,
      broken: true,
      chimney: true
    }
  },
  {
    name: 'L farmhouse',
    v: {
      ...H0,
      foot: 'L',
      roof: 'gable',
      width: 30,
      depth: 22,
      wingW: 14,
      wingP: 10,
      stories: 2,
      storyH: 9,
      found: 1.5,
      pitch: 10,
      eave: 1,
      rake: 0.75,
      wallFinish: 'siding',
      roofFinish: 'seam',
      wallColor: '#e6e5de',
      trimColor: '#fbfbf8',
      roofColor: '#3a3f45',
      windowColor: '#2a2e31',
      doorColor: '#8f2f26',
      shutterColor: '#2a2e31',
      accentColor: '#8f2f26'
    }
  },
  {
    name: 'Victorian T',
    v: {
      ...H0,
      foot: 'T',
      roof: 'gable',
      width: 30,
      depth: 24,
      wingW: 13,
      wingP: 10,
      stories: 2,
      storyH: 10,
      found: 2,
      pitch: 12,
      eave: 1,
      rake: 0.75,
      wallFinish: 'siding',
      roofFinish: 'fish',
      wallColor: '#6d7f99',
      trimColor: '#efe6d2',
      roofColor: '#5a3d46',
      windowColor: '#efe6d2',
      doorColor: '#7a2e3a',
      shutterColor: '#3e4a5c',
      accentColor: '#b58a3c',
      tower: true
    }
  },
  {
    name: 'Hip bungalow U',
    v: {
      ...H0,
      foot: 'U',
      roof: 'hip',
      width: 34,
      depth: 22,
      wingW: 11,
      wingP: 8,
      stories: 1,
      storyH: 9,
      found: 1.5,
      pitch: 6,
      eave: 1.25,
      rake: 0.75,
      wallFinish: 'stucco',
      roofFinish: 'tile',
      wallColor: '#e8dcc4',
      trimColor: '#f7f3ea',
      roofColor: '#b4583a',
      windowColor: '#5b4636',
      doorColor: '#5b4636',
      shutterColor: '#5b4636',
      accentColor: '#2e6b57'
    }
  },
  {
    name: 'Dutch gambrel',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'gambrel',
      width: 28,
      depth: 26,
      stories: 1,
      storyH: 9,
      found: 1.5,
      pitch: 8,
      eave: 1,
      rake: 0.75,
      wallFinish: 'batten',
      roofFinish: 'shake',
      wallColor: '#8f3326',
      trimColor: '#f4f1ea',
      roofColor: '#6b5847',
      windowColor: '#f4f1ea',
      doorColor: '#f4f1ea',
      shutterColor: '#3b2a22',
      accentColor: '#3b2a22',
      chimney: true
    }
  },
  {
    name: 'Cape Cod',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'gable',
      width: 32,
      depth: 24,
      stories: 1,
      storyH: 9,
      found: 1.5,
      pitch: 12,
      eave: 0.75,
      rake: 0.5,
      wallFinish: 'shingle',
      roofFinish: 'asphalt',
      wallColor: '#b9b3a6',
      trimColor: '#ffffff',
      roofColor: '#3f4448',
      windowColor: '#ffffff',
      doorColor: '#8f2f26',
      shutterColor: '#2f3e4f',
      accentColor: '#2f3e4f',
      shutters: true,
      dormers: true,
      chimney: true
    }
  },
  {
    name: 'Ranch',
    v: {
      ...H0,
      foot: 'L',
      roof: 'hip',
      width: 42,
      depth: 24,
      wingW: 20,
      wingP: 14,
      stories: 1,
      storyH: 8.5,
      found: 1,
      pitch: 5,
      eave: 1.5,
      rake: 0.75,
      wallFinish: 'brick',
      roofFinish: 'arch',
      wallColor: '#a86a4f',
      trimColor: '#f4f1ea',
      roofColor: '#5a5550',
      windowColor: '#f4f1ea',
      doorColor: '#3f5a45',
      shutterColor: '#3f5a45',
      accentColor: '#3f5a45',
      shutters: true,
      garage: true,
      chimney: false
    }
  },
  {
    name: 'Craftsman',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'gable',
      width: 30,
      depth: 26,
      stories: 1,
      storyH: 9,
      found: 2,
      pitch: 6,
      eave: 2,
      rake: 1.5,
      wallFinish: 'shingle',
      roofFinish: 'arch',
      wallColor: '#6f7a5a',
      trimColor: '#e9dfc9',
      roofColor: '#4a4038',
      windowColor: '#e9dfc9',
      doorColor: '#6a3b25',
      shutterColor: '#4a4038',
      accentColor: '#6a3b25',
      porch: 'full',
      dormers: true,
      chimney: true
    }
  },
  {
    name: 'Tudor',
    v: {
      ...H0,
      foot: 'L',
      roof: 'gable',
      width: 32,
      depth: 24,
      wingW: 14,
      wingP: 8,
      stories: 2,
      storyH: 9,
      found: 1,
      pitch: 15,
      eave: 0.75,
      rake: 0.5,
      wallFinish: 'tudor',
      roofFinish: 'slate',
      wallColor: '#efe6d0',
      trimColor: '#3b2a1f',
      roofColor: '#4a4845',
      windowColor: '#3b2a1f',
      doorColor: '#5a2e1f',
      shutterColor: '#3b2a1f',
      accentColor: '#5a2e1f',
      chimney: true,
      winStyle: 'arched'
    }
  },
  {
    name: 'Queen Anne',
    v: {
      ...H0,
      foot: 'L',
      roof: 'gable',
      width: 32,
      depth: 24,
      wingW: 13,
      wingP: 8,
      stories: 2,
      storyH: 10,
      found: 2.5,
      pitch: 14,
      eave: 1,
      rake: 0.75,
      wallFinish: 'siding',
      roofFinish: 'fish',
      wallColor: '#c9a95a',
      trimColor: '#f3ecd9',
      roofColor: '#6b3a3a',
      windowColor: '#f3ecd9',
      doorColor: '#3f5a45',
      shutterColor: '#3f5a45',
      accentColor: '#6b3a3a',
      tower: true,
      porch: 'full',
      gableFish: true,
      chimney: true
    }
  },
  {
    name: 'Lake house',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'gable',
      width: 32,
      depth: 24,
      stories: 2,
      storyH: 9,
      found: 3,
      pitch: 7,
      eave: 1.5,
      rake: 1,
      wallFinish: 'batten',
      roofFinish: 'seam',
      wallColor: '#4f6b73',
      trimColor: '#f1ede3',
      roofColor: '#2f3a3f',
      windowColor: '#f1ede3',
      doorColor: '#8a5a36',
      shutterColor: '#2f3a3f',
      accentColor: '#8a5a36',
      deck: 'rear',
      deckW: 20,
      deckD: 12,
      balcony: 'rear',
      balcW: 12,
      chimney: true
    }
  },
  {
    name: 'Mansion',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'hip',
      width: 44,
      depth: 30,
      stories: 2,
      storyH: 11,
      found: 3,
      pitch: 9,
      eave: 1.5,
      rake: 1,
      wallFinish: 'brick',
      roofFinish: 'slate',
      wallColor: '#a0523d',
      trimColor: '#f5f2ea',
      roofColor: '#3a3e44',
      windowColor: '#f5f2ea',
      doorColor: '#1f2f3f',
      shutterColor: '#1f2a24',
      accentColor: '#1f2f3f',
      shutters: true,
      porch: 'portico',
      dormers: true,
      chimney: true
    }
  },
  {
    name: 'Neo-Gothic mansion',
    v: {
      ...H0,
      foot: 'T',
      roof: 'gable',
      width: 36,
      depth: 26,
      wingW: 14,
      wingP: 10,
      stories: 2,
      storyH: 11,
      found: 2.5,
      pitch: 18,
      eave: 1,
      rake: 0.75,
      wallFinish: 'stone',
      roofFinish: 'slate',
      wallColor: '#77726c',
      trimColor: '#d8d2c4',
      roofColor: '#2e3238',
      windowColor: '#d8d2c4',
      doorColor: '#3a2a22',
      shutterColor: '#2e3238',
      accentColor: '#3a2a22',
      tower: true,
      chimney: true,
      winStyle: 'gothic'
    }
  },
  {
    name: 'Log cabin',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'gable',
      width: 30,
      depth: 22,
      stories: 1,
      storyH: 9,
      found: 1,
      pitch: 8,
      eave: 1.5,
      rake: 1,
      wallFinish: 'log',
      roofFinish: 'seam',
      wallColor: '#8a5a36',
      trimColor: '#5c3b22',
      roofColor: '#3f5a45',
      windowColor: '#efe6d2',
      doorColor: '#5c3b22',
      shutterColor: '#5c3b22',
      accentColor: '#5c3b22',
      porch: 'full',
      chimney: true
    }
  },
  {
    name: 'Mobile home',
    v: {
      ...H0,
      foot: 'rect',
      roof: 'gable',
      width: 56,
      depth: 14,
      stories: 1,
      storyH: 8,
      found: 2.5,
      pitch: 2,
      eave: 0.4,
      rake: 0.4,
      wallFinish: 'siding',
      roofFinish: 'seam',
      wallColor: '#e9e6dc',
      trimColor: '#ffffff',
      roofColor: '#d7d9d8',
      windowColor: '#ffffff',
      doorColor: '#2f6f7a',
      shutterColor: '#2f6f7a',
      accentColor: '#2f6f7a',
      shutters: true
    }
  },
  {
    name: 'Townhouse row',
    v: {
      ...H0,
      foot: 'row',
      roof: 'gable',
      units: 3,
      vary: true,
      width: 18,
      depth: 26,
      stories: 2,
      storyH: 8.5,
      found: 1.5,
      pitch: 8,
      eave: 0.75,
      rake: 0.25,
      wallFinish: 'brick',
      roofFinish: 'slate',
      wallColor: '#8e4a3a',
      trimColor: '#f1ece2',
      roofColor: '#3f454c',
      windowColor: '#f1ece2',
      doorColor: '#1f2f3f',
      shutterColor: '#1f2a24',
      accentColor: '#1f2f3f',
      shutters: true
    }
  }
];
