/* The live design settings (S) and the editor selection (EDIT). Everything the user changes lives in S. */

export const S = {
  type: 'house',
  foot: 'rect',
  width: 30,
  depth: 22,
  stories: 2,
  storyH: 9,
  found: 1.5,
  pitch: 8,
  eave: 1,
  rake: 0.75,
  roof: 'gable',
  wingW: 14,
  wingP: 12,
  units: 3,
  vary: true,
  parapet: 'cornice',
  awning: true,
  sign: 'MERCANTILE',
  roadKind: 'diner',
  bays: 2,
  canopy: true,
  shutters: true,
  custom: {},
  boarded: false,
  lit: false,
  broken: false,
  path: true,
  tileTabs: 'two',
  streetKind: 'straight',
  scCat: 'ground',
  trainCars: 3,
  storeStyle: 'classic',
  officeStyle: 'glass',
  towerTop: 'cone',
  chimney: true,
  tower: false,
  spooky: false,
  silo: true,
  civKind: 'fire',
  gKind: 'greenhouse',
  porch: 'none',
  deck: 'none',
  deckW: 16,
  deckD: 12,
  balcony: 'none',
  balcW: 10,
  dormers: false,
  garage: false,
  winStyle: 'rect',
  gableFish: false,
  venueKind: 'theater',
  indKind: 'factory',
  scKind: 'tree',
  scCount: 3,
  scH: 24,
  scL: 48,
  scW: 24,
  sidewalks: true,
  crosswalk: true,
  wallFinish: 'brick',
  roofFinish: 'asphalt',
  wallColor: '#9a4a38',
  trimColor: '#f3f0e8',
  roofColor: '#4b5056',
  windowColor: '#f3f0e8',
  doorColor: '#22382c',
  shutterColor: '#1f2a24',
  accentColor: '#22382c',
  mode: 'color',
  scale: '48',
  customDen: 84,
  paper: 'letter',
  orient: 'auto',
  thick: 'card65',
  base: true
};

export const EDIT = { key: null, sel: -1, skip: null };

export const NUM = {
  scCount: [0, 12],
  scH: [1, 80],
  scL: [4, 400],
  scW: [2, 200],
  stories: [1, 12],
  width: [8, 120],
  depth: [8, 80],
  storyH: [7, 16],
  found: [0, 4],
  pitch: [2, 18],
  eave: [0, 3],
  rake: [0, 3],
  customDen: [5, 1000],
  wingW: [6, 60],
  wingP: [4, 40],
  deckW: [6, 60],
  deckD: [4, 24],
  balcW: [5, 40]
};

export function applyPreset(v) {
  Object.assign(S, { sign: '', boarded: false, lit: false, broken: false, custom: {} }, v);
}
